theme: jekyll-theme-minimal
title: 'Introduction to Python For Bioinformatics'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Installing python3 and VSCode
    url: base/install
  - title: Bioinformatics File Types
    url: python/filetypes

  - heading: Python
  - title: Intro
    url: python/python1
  - title: Basic Data Types
    url: python/python2
  - title: Flow Control, Functions, Files, Errors
    url: python/python3
  - title: Writing Programs
    url: python/python4
  - title: Biopython and bamnostic/pysam
    url: python/python5

  - heading: ETC
  #- title: Closing Thoughts
  - title: Github Page
    url: https://github.com/ucdavis-bioinformatics-training/2022-Feb-Introduction-To-Python-For-Bioinformatics
  - title: Biocore website
    url: https://bioinformatics.ucdavis.edu/
  - title: Rosalind
    url: https://rosalind.info/problems/list-view/
